winget uninstall --id Microsoft.OneDrive
winget uninstall --id Microsoft.MicrosoftSolitaireCollection_8wekyb3d8bbwe
winget uninstall --id Microsoft.Edge
winget uninstall --id Microsoft.BingNews_8wekyb3d8bbwe
winget uninstall --id Microsoft.EdgeWebView2Runtime
winget uninstall --id Microsoft.549981C3F5F10_8wekyb3d8bbwe
winget uninstall --id Microsoft.GamingApp_8wekyb3d8bbwe
winget uninstall --id Microsoft.GetHelp_8wekyb3d8bbwe
winget uninstall --id Microsoft.Getstarted_8wekyb3d8bbwe
winget uninstall --id Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe
winget uninstall --id Microsoft.People_8wekyb3d8bbwe
winget uninstall --id Microsoft.PowerAutomateDesktop_8wekyb3d8bbwe
winget uninstall --id Microsoft.ScreenSketch_8wekyb3d8bbwe
winget uninstall --id Microsoft.StorePurchaseApp_8wekyb3d8bbwe
winget uninstall --id Microsoft.Todos_8wekyb3d8bbwe
winget uninstall --id Microsoft.WindowsAlarms_8wekyb3d8bbwe
winget uninstall --id Microsoft.WindowsCalculator_8wekyb3d8bbwe
winget uninstall --id Microsoft.WindowsCamera_8wekyb3d8bbwe
winget uninstall --id Microsoft.WindowsFeedbackHub_8wekyb3d8bbwe
winget uninstall --id Microsoft.WindowsMaps_8wekyb3d8bbwe
winget uninstall --id Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe
winget uninstall --id Microsoft.WindowsStore_8wekyb3d8bbwe
winget uninstall --id Microsoft.Xbox.TCUI_8wekyb3d8bbwe
winget uninstall --id Microsoft.XboxGameOverlay_8wekyb3d8bbwe
winget uninstall --id Microsoft.XboxIdentityProvider_8wekyb3d8bbwe
winget uninstall --id Microsoft.XboxIdentityProvider_8wekyb3d8bbwe
winget uninstall --id Microsoft.XboxSpeechToTextOverlay_8wekyb3d8bbwe
winget uninstall --id Microsoft.YourPhone_8wekyb3d8bbwe
winget uninstall --id Microsoft.ZuneMusic_8wekyb3d8bbwe
winget uninstall --id microsoft.windowscommunicationsapps_8wekyb3d8bbwe
winget uninstall --id Microsoft.OneDriveSync_8wekyb3d8bbwe
winget uninstall --id Microsoft.MicrosoftEdge.Stable_8wekyb3d8bbwe
